// <auto-generated />
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    [Migration("20201104145847_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidad.Habitacion", b =>
                {
                    b.Property<string>("Idhabitacion")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Usos")
                        .HasColumnType("int");

                    b.HasKey("Idhabitacion");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("Entidad.Producto", b =>
                {
                    b.Property<string>("Idproducto")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("Vrunitario")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Idproducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Entidad.Usuario", b =>
                {
                    b.Property<string>("Iduser")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Typeuser")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Iduser");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
